name: "Generate Documentation"

on:
    push:
        branches:
            - "main"

jobs:
    "GenerateDocumentation":
        uses: LebJe/SwiftWorkflows/.github/workflows/generateDocumentation.yml@main
        with:
            TargetName: "ICMPPing"
            DoccBundlePath: "Sources/ICMPPing/ICMPPing.docc"
